set positional-arguments

glo := "__GLO__"

default:
    @just --list

shell *args:
    #!/bin/bash
    just -f {{glo}}/devcontainer/justfile --set workspace "$PWD" shell "$@"

precommit:
    bin/glo-build --filter=work precommit
    bin/glo-notes precommit
